need2fix/app/urls.py
from django.urls import path
from app.views import task_list, task_add, task_detail
urlpatterns = [
    path('list/', task_list, name='task-list'),
    path('add/', task_add, name='task-add'),
    path('detail/<int:pk>/', task_detail, name='task-detail'),
]

need2fix/need2fix/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app.routers import router
from app.views import home, task_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', task_list, name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('task/', include(('app.urls', 'app'), namespace='app')),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

need2fix/app/models.py
import os
import json
import pytz
from django.utils import timezone
from django.db import models
from django.db import transaction
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from app import building_info, division_list

def get_upload_path(instance, filename):
    return os.path.join(instance.requester.username, filename)


usermodel = get_user_model()


class Task(models.Model):
    STATUS_CHOICES = [
        ('1', 'รับเรื่อง'),
        ('2', 'ดำเนินการ'),
        ('3', 'เสร็จสิ้น'),
    ]

    DIVISION_CHOICES = [(k, v) for k, v in division_list.items()]


    title = models.CharField(max_length=64)
    description = models.CharField(max_length=512)
    building = models.CharField(max_length=32)
    floor = models.CharField(max_length=32)
    room = models.CharField(max_length=32, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    done_date = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=1, blank=True, choices=STATUS_CHOICES)
    division = models.CharField(max_length=2, blank=True, choices=DIVISION_CHOICES, null=True)
    image = models.ImageField(upload_to=get_upload_path, null=True, blank=True)
    requester = models.ForeignKey(usermodel, blank=True, on_delete=models.PROTECT, related_name='request_set')
    operator = models.ForeignKey(usermodel, null=True, blank=True, on_delete=models.SET_NULL, related_name='task_set')

    @transaction.atomic
    def save(self, *args, **kwargs):
        if not self.pk:
            self.status = '1'
            if 'user' in kwargs:
                self.requester = kwargs['user']
        self.full_clean()
        if self.status == '3':
            self.done_date = timezone.now()
        super(Task, self).save(*args, **kwargs)
        
    def clean(self, *args, **kwargs):
        if self.status in ('2', '3') and not self.operator:
            raise ValidationError('Null Operator exeption')        
        if self.operator and not self.operator.groups.filter(name='mechanic'):
            raise ValidationError('Operator must be in Mechanic group.')

        if self.building in building_info:
            if self.floor in building_info[self.building]:
                if self.room in building_info[self.building][self.floor]:
                    pass
                else:
                    raise ValidationError('invalid room available room are {}'\
                        .format(list(building_info[self.building][self.floor])))
            else:
                raise ValidationError('invalid floor available floor are {}'\
                    .format(list(building_info[self.building])))
        else:
            raise ValidationError('invalid building available building are {}'\
                .format(list(building_info)))
        return True

need2fix/app/forms.py
from django import forms
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.admin import widgets
from app.models import Task

class TaskForm(ModelForm):

    class Meta:
        model =  Task
        fields = ('status', )

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))

need2fix/app/views.py
import json
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from app.models import Task

#@login_required
def task_list(request):
    return render(request, 'app/task_list.html')

@login_required
def task_add(request):
    return render(request, 'app/task_add.html')

@login_required
def task_detail(request, pk):
    context = {'pk': pk}
    return render(request, 'app/task_detail.html', context)


def home(request):
    return render(request, 'app/home.html')

need2fix/app/templates/app/task_add.html
{% extends 'base.html' %}
{% block title %} แจ้งซ่อม {% endblock %}
{% block content %}
<div style="margin:50px;">
<div id='content'>
  <form class="uk-form-horizontal">
    <fieldset class="uk-fieldset">
      <legend class="uk-legend"> กรุณากรอกข้อมูลแจ้งซ่อม </legend>
      <div class="uk-margin">
        <input class="uk-input" type="text" placeholder="หัวเรื่อง" v-model="formInput.title">
      </div>
      <div class="uk-margin">
        <label> ถึง </label>
        <select class="uk-select" v-model="formInput.division">
          <option v-for="(description, division) in divisionList" v-bind:value="division"> [[description]] </option>
        </select>
      </div>
      <div class="uk-margin">
        <textarea class="uk-textarea" rows="5" placeholder="คำธิบาย" v-model="formInput.description"></textarea>
      </div>
      <div class="uk-margin">
        <label> อาคาร </label>
        <select class="uk-select" v-model="formInput.building">
          <option v-for="(info, building) in buildingInfo"> [[building]] </option>
        </select>
      </div>
      <div class="uk-margin" v-if="formInput.building">
        <label> ชั้น </label>
        <select class="uk-select" v-model="formInput.floor">
          <option v-for="(info, floor) in buildingInfo[formInput.building]"> [[floor]] </option>
        </select>
      </div>
      <div class="uk-margin" v-if="formInput.floor">
        <label> ห้อง </label>
        <select class="uk-select" v-model="formInput.room">
          <option v-for="room in buildingInfo[formInput.building][formInput.floor]"> [[room]] </option>
        </select>
      </div>
      <div class="js-upload" uk-form-custom>
        <input type="file" ref='imageUpload' v-on:change="imageHandle()">
        <button class="uk-button uk-button-default" type="button" tabindex="-1">เพิ่มรูปภาพ</button>
      </div>
      <button class="uk-button uk-button-default" type="button" tabindex="-1" v-if="previewImage" v-on:click="clearImage">ล้าง</button>
      <image class="imagePreviewer" v-bind:src="previewImage" v-if="imageFile!=null"> </image>
    </fieldset>
  </form>
  <br>
  <button class="uk-button uk-button-default" v-on:click="submitRequest()"  v-bind:disabled="checkSubmitable()">ส่งคำร้อง</button>
</div>
<style type="text/css">
  .imagePreviewer {
    width: 400px;
    background-color: white;
    border: 1px solid #DDD;
    padding: 5px;
  }
</style>
{% endblock %}

{% block script %}
<script type="text/javascript">
new Vue({
  el: '#content',
  delimiters: ['[[', ']]'],

  mounted () {
    axios.get('/api/building-info')
      .then((res) => {
        this.buildingInfo = res.data
      })
    axios.get('/api/division-list')
      .then((res) => {
        this.divisionList = res.data
        this.divisionList[null] = "ไม่ระบุ"
      })
  },

  data: function () {
    return {
      'buildingInfo': {},
      'divisionList': {},
      'formInput': {},
      'imageFile': null,
      'previewImage': null
    }
  },

  methods: {
    clearImage: function () {
      this.previewImage = null
      this.imageFile = null
    },

    imageHandle: function() {
      this.imageFile = this.$refs.imageUpload.files[0]
      var reader = new FileReader();
        reader.onload = (e) => {
          this.previewImage = e.target.result;
        }
        reader.readAsDataURL(this.imageFile);
    },

    checkSubmitable: function() {
      let checklist = ['title', 'description', 'building', 'floor', 'room']
      try{
        checklist.forEach( (d) => {
          if (this.formInput[d]=='') throw BreakException
        })
        return false
      } catch (e) {
        return true
      }
    },

    clearForm: function () {
      this.formInput.title = ''
      this.formInput.description = ''
      this.formInput.building = ''
      this.formInput.floor = ''
      this.formInput.room = ''
      this.clearImage()
    },

    submitRequest: function () {

      let formData = new FormData()
      for (let key in this.formInput ) {
        if (this.formInput[key] != "null") {
          formData.set(key, this.formInput[key])
        }
      }
      if (this.imageFile) {
        formData.set('image', this.imageFile)
      } 

      axios.post('/api/task/', formData)
        .then((res) => {
          alert('ส่งคำร้องเรียบร้อย')
          this.clearForm()
        })
        .catch((error) => {
          s = 'เกิดข้อผิดพลาด'
          for(let k in error.response.data) {
            s += '\n' + k + ': ' + error.response.data[k]
          }
          alert(s)

        })
    }
  }
})
</script>
{% endblock %}

need2fix/app/templates/app/task_detail.html
{% extends 'base.html' %}
{% block title %} งานซ่อม {% endblock %}
{% block content %}
  <div><p>jghgj</p>
  <div id='content'>
    <!-- Editable  -->
    <form class="uk-form-horizontal" >
      <fieldset class="uk-fieldset">
        <legend class="uk-legend"> คำร้องที่ {{pk}} </legend>
        <label>สถานะ</label>
        <select select class="uk-select" v-model="formData.status">
          <option value="1">รับเรื่อง</option>
          <option value="2">ดำเนินการ</option>
          <option value="3">เสร็จสิ้น</option>
        </select>
        <label>ผู้รับผิดชอบ</label>
        <select select class="uk-select" v-model="formData.operator">
          <option v-for="mec in mechanicList" v-bind:value="mec.id"> [[mec.username]] [[mec.first_name]] </option>
        </select>
      </fieldset>
    </form>
    <button class="uk-button uk-button-default" v-on:click="updateRequest()">ส่งคำร้อง</button>

    <!-- ReadOnly -->
    <div class="uk-margin"style="margin:10%"  >
      <label >หัวเรื่อง</label>
      <input class="uk-input" type="text" placeholder="หัวเรื่อง" v-model="formData.title" disabled>
    </div>
    <div class="uk-margin">
      <label> ถึง: [[divisionName]] </label>
    </div>
    <div class="uk-margin">
      <label>คำอธิบาย</label>
      <textarea class="uk-textarea" rows="5" placeholder="คำธิบาย" v-model="formData.description" disabled></textarea>
    </div>
    <div class="uk-margin">
      <label> อาคาร: [[formData.building]] </label>
    </div>
    <div class="uk-margin">
      <label> ชั้น: [[formData.floor]] </label>
    </div>
    <div class="uk-margin">
      <label> ห้อง: [[formData.room]] </label>
    </div>
    <image class="imagePreviewer" v-bind:src="formData.image" v-if="formData.image!=null"> </image>
  </div>
  </div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
var content = new Vue({
  el: '#content',
  delimiters: ['[[', ']]'],
  data: function () {
    return {
      'formData': {},
      'divisionList': {},
      'mechanicList': []
    }
  },
  
  computed: {
    divisionName: function () {
      return this.formData.division? this.divisionList[this.formData.division]: 'ไม่ระบุ'
    }
  },

  mounted: function () {
    axios.get('/api/division-list/')
      .then((response) => {
        this.divisionList = response.data
      })
      .catch((error) => {
        alert(error)
      })    
    axios.get('/api/mechanic-list/')
      .then((response) => {
        this.mechanicList = response.data
      })
      .catch((error) => {
        alert(error)
      })
    axios.get('/api/task/'+'{{pk}}/')
      .then((response) => {
        this.formData = response.data
      })
      .catch((error) => {
        alert(error)
      })
  }, 

  methods: {
    updateRequest: function () {
      if (confirm("ยืนยันการแก้ไข")) {
        axios.put('/api/task/'+'{{pk}}/', this.formData)
          .then((response) => {
            console.log(response.data)
          })
          .catch((error) => {
            s = 'เกิดข้อผิดพลาด'
            for(let k in error.response.data) {
              s += '\n' + k + ': ' + error.response.data[k]
            }
            alert(s)
          })
      }
    }
  }

})
</script>
{% endblock %}

need2fix/app/templates/app/task_list.html
{% extends 'base.html' %}
{% block title %} งานซ่อม {% endblock %}
{% block content %}

<div id='content' style="margin-top:5%">
  <form  style="text-align:center">
    <input type='radio' value='0' v-model='filterStatus' > ทั้งหมด 
    <input type='radio' value='1' v-model='filterStatus'style="margin-left:3%"> รับเรื่อง
    <input type='radio' value='2' v-model='filterStatus'style="margin-left:3%"> ดำเนินการ
    <input type='radio' value='3' v-model='filterStatus'style="margin-left:3%"> เสร็จสิ้น
  </form>
  {% if user.is_authenticated %}
  <form>
    <input type='checkbox' value='true' v-model='onlyMe' style="margin-left:5%"> งานของฉัน
  </form>
  {% endif %}
  <table class='uk-table uk-table-striped uk-table-hover  uk-table-small'>
    <caption style="margin-left:1%">งานแจ้งซ่อม</caption>
    <thead>
      <tr style="background-color:rgb(247, 238, 189);margin-left:3%;" >
        <th style="color:rgb(52, 52, 54)"> หัวเรื่อง </th>
        <th style="color:rgb(52, 52, 54)"> ฝ่าย </th>
        <th style="color:rgb(52, 52, 54)"> คำอธิบาย </th>
        <th style="color:rgb(52, 52, 54)"> ตึก </th>
        <th style="color:rgb(52, 52, 54)"> ชั้น </th>
        <th style="color:rgb(52, 52, 54)"> ห้อง </th>
        <th style="color:rgb(52, 52, 54)"> สถานะ </th>
      </tr>
    </thead>
    <tbody v-for='task in taskList'>
      <tr v-if='(onlyMe==false & (filterStatus==0 | task.status==filterStatus)) |
                ({{user.id}}!="None" & onlyMe==true & 
                  (filterStatus==0 | task.status==filterStatus) & 
                  (task.requester=={{user.id}} | task.operator=={{user.id}})
                )'>
        <td> <a v-bind:href="'/task/detail/'+task.id+'/'">[[task.title]]</a></td>
        <td>[[divisionName(task.division)]]</td>
        <td>[[task.description]]</td>
        <td>[[task.building]]</td>
        <td>[[task.floor]]</td>
        <td>[[task.room]]</td>
        <td>[[task.status==1? 'รับเรื่อง':task.status==2?'ดำเนินการ':'เสร็จสิ้น']]</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
var content = new Vue({
  el: '#content',
  delimiters: ['[[', ']]'],
  data: function () {
    return {
      'message': 'Hello',
      'taskList': null,
      'filterStatus': 1,
      'onlyMe': false,
      'divisionList': []
    }
  },

  methods: {
    divisionName: function (division) {
      return division? this.divisionList[division]: 'ไม่ระบุ'
    }
  },

  mounted: function () {
    axios.get('/api/task/')
      .then((response) => {
        this.taskList = response.data
      })
      .catch((error) => {
        alert(error)
      })
    axios.get('/api/division-list/')
      .then((response) => {
        this.divisionList = response.data
      })
      .catch((error) => {
        alert(error)
      })   
  }
})
</script>
{% endblock %}

need2fix/app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title> {% block title %} {% endblock %}</title>
</head>
<body>
<script src="{% static 'js/vue.js' %}"></script>
<script src="{% static 'js/axios.min.js' %}"></script>
<script type="text/javascript">
  axios.defaults.headers.common['X-CSRFToken'] = '{{csrf_token}}'
</script>
<link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" />
<script src="{% static 'js/uikit.min.js' %}"></script>
<script src="{% static 'js/uikit-icons.min.js' %}"></script>
<div id="app">
  <div class="uk-position-relative">
    <nav class="uk-navbar-container" uk-navbar="dropbar: true" style="background:linear-gradient(to bottom right,darkred,rgb(80, 3, 3) )">
        <div class="uk-navbar-left">
          <img src="../../static/img/a.png" style="width:300px; margin: 10px;" />
        </div>
        <div class="uk-navbar-left">
            <ul class="uk-navbar-nav">
              <li> <a style="color:white" href="{% url 'home' %} "> หน้าหลัก </a> </li>
              <li> <a style="color:white" href="{% url 'app:task-list' %}"> คำขอ </a> </li>
              <li> <a style="color:white" href="{% url 'app:task-add' %}"> แจ้งซ่อม </a> </li>
            </ul>
            
        </div>
        <div class="uk-navbar-right" style="margin-right:5%;">
          {% if request.user.is_authenticated %}
            <article class="uk-comment">
              <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
                <div class="uk-width-auto">
                  <img class="uk-comment-avatar" src="{% static 'img/avatar.png' %}" alt="">
                </div>
                <div class="uk-width-auto">
                  <h4 class="uk-comment-title uk-margin-remove" style="color:white"><a class="uk-link-reset" href="#" > {{user.username}} </a></h4>
                  <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                    <li><a href="#" style="color:white">setting</a></li>
                    <li><a href="#" style="color:white">logout</a></li>
                  </ul>
                </div>
              </header>
            </div>
          {% else %}
            <form action="{% url 'social:begin' 'tu' %}">
              <input class="uk-button uk-button-primary" type="submit" value='TU Login'>
            </form>
          {% endif %}
        </div>
        

    </nav>

    <!-- <div class="uk-navbar-dropbar"></div> -->

</div>
</div>
{% block content %} {% endblock %}
<script type="text/javascript">
var app = new Vue({
  el: '#app',
  delimiters: ['[[', ']]'],
  data: function () {
  return {}
  }
})
</script>
{% block script %} {% endblock %}
</body>
</html>